config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => '/good_job'
    mount Motor::Admin => '/admin'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root 'root#index'
  get 'direct_close' => 'root#direct_close', as: :direct_close
  get 'tos' => 'root#tos', as: :tos
  get 'privacy_policy' => 'root#privacy_policy', as: :privacy_policy

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :users, only: %i[] do
    collection do
      get 'me' => 'users#me'
    end
  end
  namespace :users do
    resources :reminder_settings, only: %i[create update]
    resources :summary_settings, only: %i[create update]
  end

  namespace :links do
    resources :tags, only: %i[index new create show edit update destroy]
  end
  resources :links, only: %i[index show new create edit update destroy] do
    collection do
      get 'others' => 'links#others'
    end
    member do
      put 'read' => 'links#read'
      put 'unread' => 'links#unread'
      post 'clone' => 'links#clone'
    end

    scope module: :links do
      resource :records, only: %i[show create edit update destroy]
    end
  end

  resources :settings, only: %i[] do
    collection do
      get 'general' => 'settings#general'
      get 'summary' => 'settings#summary'
      get 'notification' => 'settings#notification'
      get 'tag' => 'settings#tag'
    end
  end

  resources :notifications, only: %i[index]

  namespace :admin do
    resources :links, only: [] do
      collection do
        post 'initial' => 'links#create_initial'
      end
    end
  end
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  include Discard::Model
  include Taggable
  include Links::Scraping
  include Links::Searchable
  include Links::Readable
  include Links::Remindable

  belongs_to :user
  has_one :record, dependent: :destroy, class_name: 'Links::Record'
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings, class_name: 'Links::Tag'

  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :url, presence: true, uniqueness: { scope: :user_id }
  # rubocop:enable Rails/UniqueValidationWithoutIndex
  validates :due_date,
            comparison: { greater_than_or_equal_to: -> { Time.current.to_date }, allow_nil: true },
            if: :due_date_changed?

  before_validation :set_default_due_date, if: -> { due_date.blank? }, on: :create

  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  after_create_commit { broadcast_refresh_to [user, 'links'] }
  after_update_commit do
    I18n.with_locale(user.locale) do
      broadcast_replace_to [user, 'links'], locals: { link: self, current_user: user }
    end
    broadcast_refresh
  end
  after_discard do
    broadcast_remove_to [user, 'links']
    record.discard if record&.persisted?
  end
  after_undiscard -> { record&.undiscard }

  def clone(user_id)
    dup.tap do |link|
      link.user_id = user_id
      link.due_date = nil
      link.created_at = nil
    end
  end

  private

  def set_default_due_date
    self.due_date = user&.summary_setting&.default_due_days&.days&.from_now&.to_date
  end
end

app/models/link/readable.rb
# frozen_string_literal: true

module Link::Readable
  extend ActiveSupport::Concern

  def read!
    update!(read_at: Time.current)
  end

  def unread!
    update!(read_at: nil)
  end

  def read?
    read_at.present?
  end

  def unread?
    !read?
  end
end

app/models/link/scraping.rb
# frozen_string_literal: true

module Link::Scraping
  extend ActiveSupport::Concern

  included do
    enum scraping_state: { initial: 0, scraping: 1, completed: 2, failed: 3 }

    after_create_commit :scrap_later, if: :initial?
  end

  def scrap_now
    LinkScrapingJob.perform_now(self)
  end

  private

  def scrap_later
    LinkScrapingJob.perform_later(self)
  end
end

app/models/link/searchable.rb
# frozen_string_literal: true

module Link::Searchable
  extend ActiveSupport::Concern

  class_methods do
    def ransackable_attributes(_auth_object = nil)
      %w[title read_at]
    end

    def ransortable_attributes(_auth_object = nil)
      %w[id due_date]
    end
  end
end

app/models/links/application_record.rb
# frozen_string_literal: true

class Links::ApplicationRecord < ApplicationRecord
  self.abstract_class = true
  self.table_name_prefix = 'links_'
end

app/models/links/crawl_result.rb
# frozen_string_literal: true

class Links::CrawlResult
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :title, :string
  attribute :image_url, :string
  attribute :outline, :string
end

app/models/links/readable.rb
# frozen_string_literal: true

module Links::Readable
  extend ActiveSupport::Concern

  included do
    scope :read, -> { where.not(read_at: nil) }
    scope :unread, -> { where(read_at: nil) }
  end

  def read!
    update!(read_at: Time.current)
  end

  def unread!
    update!(read_at: nil)
  end

  def read?
    read_at.present?
  end

  def unread?
    !read?
  end

  def must_read?
    unread? && due_date.present?
  end
end

app/models/links/record.rb
# frozen_string_literal: true

class Links::Record < Links::ApplicationRecord
  include Discard::Model

  belongs_to :link

  validates :link, uniqueness: true
  validates :content, presence: true
end

app/models/links/remind_info.rb
# frozen_string_literal: true

class Links::RemindInfo
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Serializers::JSON

  attribute :id, :integer
  attribute :title, :string
  attribute :summary, :string
  attribute :due_date, :date
  attribute :url, :string
  attribute :created_at, :datetime

  def attributes
    {
      'id' => nil,
      'title' => nil,
      'summary' => nil,
      'due_date' => nil,
      'url' => nil,
      'created_at' => nil,
    }
  end
end

app/models/links/remindable.rb
# frozen_string_literal: true

module Links::Remindable
  extend ActiveSupport::Concern

  included do
    scope :remind_target, ->(criteria_days) do
      unread.where(due_date: ..criteria_days.days.from_now.to_date).order(due_date: :asc)
    end
  end

  def to_remind_info
    Links::RemindInfo.new(id:, title:, due_date:, url:, created_at:)
  end
end

app/models/links/searchable.rb
# frozen_string_literal: true

module Links::Searchable
  extend ActiveSupport::Concern

  class_methods do
    def ransackable_attributes(_auth_object = nil)
      %w[title read_at]
    end

    def ransortable_attributes(_auth_object = nil)
      %w[id due_date]
    end

    def ransackable_associations(_auth_object = nil)
      %w[tags]
    end
  end
end

app/models/links/tag.rb
# frozen_string_literal: true

class Links::Tag < Tag
  has_many :links, through: :taggings, source: :taggable, source_type: 'Link'

  scope :by_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
  scope :with_user, ->(user) { where(user:) }
  scope :with_user_id, ->(user_id) { where(user_id:) }
end

app/controllers/admin/links_controller.rb
# frozen_string_literal: true

class Admin::LinksController < Admin::ApplicationController
  def create_initial
    Link.create!(link_params)
  end

  private

  def link_params
    params.require(:link).permit(:url, :user_id, :due_date)
  end
end

app/controllers/links/records_controller.rb
# frozen_string_literal: true

class Links::RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link
  before_action :set_record, only: %i[show edit update destroy]

  def show; end

  def edit; end

  def create
    @record = @link.build_record(record_params)

    if @record.save
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = @record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  def update
    if @record.update(record_params)
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  def destroy
    if @record.destroy
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  private

  def set_link
    @link = current_user.links.find(params[:link_id])
  end

  def set_record
    @record = @link.record || @link.build_record
  end

  def record_params
    params.require(:links_record).permit(:link_id, :content)
  end

  def render_record
    render turbo_stream: turbo_stream.replace(
      [@link, 'record'],
      partial: 'links/records/record',
      locals: { record: @record },
    )
  end
end

app/controllers/links/tags_controller.rb
# frozen_string_literal: true

class Links::TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[edit update destroy]

  def index
    tags = Links::Tag.with_user(current_user).by_name(params[:q]).limit(10).pluck(:name)
    tags.unshift(params[:q]) if tags.exclude?(params[:q])

    respond_to do |format|
      format.json do
        render json: tags.map { |tag| { value: tag, text: tag } }
      end
    end
  end

  def new
    @tag = Links::Tag.new
  end

  def edit; end

  def create
    @tag = Links::Tag.new(tag_params.merge(user: current_user))
    if @tag.save
      redirect_to tag_settings_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tag_settings_path, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @tag.destroy
      redirect_to tag_settings_path, notice: t('.success')
    else
      flash.now[:alert] = @tag.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  private

  def tag_params
    params.require(:links_tag).permit(:name)
  end

  def set_tag
    @tag = Links::Tag.with_user(current_user).find(params[:id])
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  include Searchable

  before_action :authenticate_user!, except: %i[show]
  before_action :set_link, only: %i[edit update destroy read unread]

  MAX_ITEMS = 20

  def index
    @q = current_user.links.kept.includes(:tags).ransack(search_params)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @pagy, @links = pagy(@q.result(distinct: true), items: MAX_ITEMS)

    respond_to do |format|
      format.html
      format.json { render json: @links }
    end
  end

  def others
    links_with_distinct_url = Link.select('DISTINCT ON (url) *')
                                  .kept
                                  .completed
                                  .where.not(user_id: current_user.id)

    @q = Link.from(links_with_distinct_url, :links).ransack(search_params)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @pagy, @links = pagy(@q.result, items: MAX_ITEMS)
  end

  def show
    @link = Link.kept.find(params[:id])
    @link.build_record if @link.record.blank?
  end

  def new
    @link = current_user.links.build
  end

  def edit; end

  def create
    @link = current_user.links.build(link_params)

    if @link.save
      respond_to do |format|
        format.json { render json: @link }
        format.html do
          flash[:notice] = t('.success')
          redirect_to link_path(@link)
        end
      end
    else
      logger.error @link.errors

      respond_to do |format|
        format.json { render json: @link.errors.full_messages, status: :unprocessable_entity }
        format.html do
          flash.now[:alert] = @link.errors.full_messages.first || t('.failure')
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    if @link.update(update_link_params)
      flash[:notice] = t('.success')
      redirect_to link_path(@link)
    else
      flash.now[:alert] = @link.errors.full_messages.first || t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.discard!
  end

  def read
    @link.read!
    render turbo_stream: turbo_stream.replace(
      [@link, 'menu'],
      partial: 'links/menu',
      locals: { link: @link },
    )
  end

  def unread
    @link.unread!
    render turbo_stream: turbo_stream.replace(
      [@link, 'menu'],
      partial: 'links/menu',
      locals: { link: @link },
    )
  end

  def clone
    cloned_link = Link.kept.find(params[:id]).clone(current_user.id)

    if cloned_link.save
      flash.now[:notice] = t('.clone.success')
    else
      flash.now[:alert] = cloned_link.errors.full_messages.first || t('.clone.failure')
    end

    render partial: 'shared/flash'
  end

  private

  def link_params
    params.require(:link).permit(:url, :due_date, tag_names: [])
  end

  def update_link_params
    params.require(:link).permit(:due_date, tag_names: [])
  end

  def set_link
    @link = current_user.links.kept.find(params[:id])
  end
end

app/helpers/link_helper.rb
# frozen_string_literal: true

module LinkHelper
  def link_until_due_date(due_date)
    distance_in_day = (due_date - Date.current).to_i

    classes = case distance_in_day
              when ..0
                'text-red-700 font-semibold'
              when 1..3
                'text-yellow-800 font-medium'
              when 4..7
                'text-blue-700 font-normal'
              else
                'text-green-700 font-normal'
              end

    content_tag :span, class: classes do
      if distance_in_day.negative?
        t('common.overdue')
      else
        left_time = distance_of_time_in_words(due_date.end_of_day, Time.current)
        t('common.some_left', value: left_time)
      end
    end
  end

  def link_sort_text_and_values
    [
      [t('links.index.newest'), 'id desc'],
      [t('links.index.oldest'), 'id asc'],
      [t('links.index.closest_due_date'), 'due_date asc'],
      [t('links.index.farthest_due_date'), 'due_date desc'],
    ]
  end

  def link_others_sort_text_and_values
    [
      [t('links.index.newest'), 'id desc'],
      [t('links.index.oldest'), 'id asc'],
    ]
  end

  def link_current_sort_value
    return nil if @q.sorts.empty?

    [@q.sorts.first.name, @q.sorts.first.dir].join(' ')
  end

  def link_image(url)
    url.presence || asset_path('default_background.png')
  end
end

app/views/links/records/_form.html.erb
<%# locals: (record:) %>

<div class="border-t border-gray-900/10 mt-12 pt-12">
  <h1 class="text-base sm:text-lg font-medium"><%= t '.title' %></h1>
</div>

<%= form_with model: record,
              url: link_records_path(record.link),
              class: 'mt-4 space-y-6',
              data: {
                controller: 'tabs',
                tabs_active_tab_class: 'bg-gray-100 text-gray-900 hover:bg-gray-200',
                tabs_inactive_tab_class: 'bg-white text-gray-500 hover:bg-gray-100 hover:text-gray-900',
                turbo_permanent: true
              } do |f| %>
  <div data-controller="markdown-preview">
    <div class="flex items-center">
      <%= button_tag t('.write'),
                     type: 'button',
                     class: 'rounded-md border border-transparent px-3 py-1.5 text-sm font-medium',
                     data: { tabs_target: 'tab', action: 'click->tabs#change' }%>
      <%= button_tag t('.preview'),
                     type: 'button',
                     class: 'ml-2 rounded-md border border-transparent px-3 py-1.5 text-sm font-medium',
                     data: { tabs_target: 'tab', action: 'click->tabs#change' }%>
    </div>

    <div class="mt-2">
      <div class="-m-0.5 rounded-lg p-0.5" data-tabs-target="panel">
        <div>
          <%= f.text_area :content,
                          rows: 5,
                          placeholder: t('.placeholder'),
                          class: 'block w-full rounded-md border-0 p-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 text-sm sm:text-base sm:leading-6',
                          data: { markdown_preview_target: 'input', action: 'input->markdown-preview#render' } %>
        </div>
      </div>

      <div class="-m-0.5 rounded-lg p-0.5" data-tabs-target="panel">
        <div class="border-b ring-1 ring-inset ring-gray-300 rounded-md">
          <div class="max-w-full mx-px mt-px p-4 text-sm leading-5 text-gray-800 prose" data-markdown-preview-target="output">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-end gap-x-6 items-center">
    <%= link_to t('.cancel'), link_records_path(record.link), class: 'text-sm font-semibold leading-6 text-gray-900', data: { turbo_stream: true } %>
    <%= f.submit t('.save'), class: 'cursor-pointer inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
  </div>
<% end %>

app/views/links/records/_record.html.erb
<%# locals: (record:) %>

<%= turbo_frame_tag record.link, 'record' do %>
  <% if record.persisted? %>
    <%= render 'links/records/show', record: %>
  <% else %>
    <%= render 'links/records/form', record: %>
  <% end %>
<% end %>

app/views/links/records/_show.html.erb
<%# locals: (record:) %>

<div class="border-t border-gray-900/10 mt-12 pt-12 flex justify-between">
  <h1 class="text-base sm:text-lg font-medium"><%= t '.title' %></h1>

</div>

<div class="mt-3 ring-1 ring-inset ring-gray-300 rounded-md space" data-controller="markdown-preview">
  <div class="flex flex-row justify-between p-3 bg-gray-100 ring-1 ring-inset ring-gray-300 rounded-t-md">
    <span class="text-gray-500 text-sm">
      <%= relative_time(record.link.created_at) %>
    </span>

    <div class="flex flex-row py-0.5 text-sm">
      <%= link_to t('.edit'), edit_link_records_path(record.link), class: 'text-indigo-600 hover:text-indigo-500 pl-3', data: { turbo_stream: true } %>
      <%= link_to t('.delete'), link_records_path(record.link), class: 'text-indigo-600 hover:text-indigo-500 ml-3 border-l border-gray-200 pl-3', data: { turbo_stream: true, turbo_method: :delete, turbo_confirm: t('.confirm_delete') } %>
    </div>
  </div>

  <%= hidden_field :record, :content, value: record.content, data: { markdown_preview_target: 'input' } %>
  <div class="prose max-w-full w-full p-4" data-markdown-preview-target="output"></div>
</div>

app/views/links/records/edit.turbo_stream.erb
<%= turbo_stream.update [@link, 'record'] do %>
  <%= render 'form', record: @record %>
<% end %>

app/views/links/records/show.turbo_stream.erb
<%= turbo_stream.update [@link, 'record'] do %>
  <%= render @record %>
<% end %>