config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => '/good_job'
    mount Motor::Admin => '/admin'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root 'root#index'
  get 'direct_close' => 'root#direct_close', as: :direct_close
  get 'tos' => 'root#tos', as: :tos
  get 'privacy_policy' => 'root#privacy_policy', as: :privacy_policy

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :users, only: %i[] do
    collection do
      get 'me' => 'users#me'
    end
  end
  namespace :users do
    resources :reminder_settings, only: %i[create update]
    resources :summary_settings, only: %i[create update]
  end

  namespace :links do
    resources :tags, only: %i[index new create show edit update destroy]
  end
  resources :links, only: %i[index show new create edit update destroy] do
    collection do
      get 'others' => 'links#others'
    end
    member do
      put 'read' => 'links#read'
      put 'unread' => 'links#unread'
      post 'clone' => 'links#clone'
    end

    scope module: :links do
      resource :records, only: %i[show create edit update destroy]
    end
  end

  resources :settings, only: %i[] do
    collection do
      get 'general' => 'settings#general'
      get 'summary' => 'settings#summary'
      get 'notification' => 'settings#notification'
      get 'tag' => 'settings#tag'
    end
  end

  resources :notifications, only: %i[index]

  namespace :admin do
    resources :links, only: [] do
      collection do
        post 'initial' => 'links#create_initial'
      end
    end
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :authenticate_user!

  def general; end

  def summary
    @summary_setting = current_user.summary_setting || current_user.build_summary_setting
  end

  def notification
    @reminder_setting = current_user.reminder_setting || current_user.build_reminder_setting
  end

  def tag
    @tags = Links::Tag.with_user(current_user).order(id: :desc)
    @tag = Links::Tag.new
  end
end

app/helpers/setting_helper.rb
# frozen_string_literal: true

module SettingHelper
  def setting_language_and_locale_options
    options_for_select(
      { 'English' => 'en', '한국어' => 'ko' },
      current_user.locale,
    )
  end

  def setting_days_options
    t('date.abbr_day_names').zip(DateAndTime::Calculations::DAYS_INTO_WEEK.keys)
  end
end

app/views/settings/_sidebar.html.erb
<aside class="flex overflow-x-auto border-b border-gray-900/5 py-4 lg:block lg:w-64 lg:flex-none lg:border-0 lg:py-0">
  <nav class="flex-none px-4 sm:px-6 lg:px-0">
    <ul role="list" class="flex gap-x-3 gap-y-1 whitespace-nowrap lg:flex-col">
      <li>
        <%= link_to general_settings_path, class: "#{current_page?(controller: '/settings', action: 'general') ? 'bg-gray-50 text-indigo-600' : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'} group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold" do %>
          <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          <%= t '.general' %>
        <% end %>
      </li>
      <li>
        <%= link_to summary_settings_path, class: "#{current_page?(controller: '/settings', action: 'summary') ? 'bg-gray-50 text-indigo-600' : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'} group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
          </svg>
          <%= t('.summary') %>
      <% end %>
      </li>
      <li>
        <%= link_to notification_settings_path, class: "#{current_page?(controller: '/settings', action: 'notification') ? 'bg-gray-50 text-indigo-600' : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'} group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold" do %>
          <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
          <%= t '.notification' %>
        <% end %>
      </li>
      <li>
        <%= link_to tag_settings_path, class: "#{current_page?(controller: '/settings', action: 'tag') ? 'bg-gray-50 text-indigo-600' : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'} group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6Z" />
          </svg>
          <%= t '.tag' %>
        <% end %>
      </li>
<!--      <li>-->
        <%#= link_to '#', class: "#{!current_page?(controller: '/settings', action: 'general') ? 'bg-gray-50 text-indigo-600' : 'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'} group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold" do %>
<!--          <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">-->
<!--            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z" />-->
<!--          </svg>-->
<!--          Billing-->
        <%# end %>
<!--      </li>-->
    </ul>
  </nav>
</aside>

app/views/settings/general.html.erb
<div class="w-full lg:flex lg:gap-x-16 lg:px-8 lg:mt-4">
  <%= render 'sidebar' %>

  <div class="px-4 py-16 py-20 lg:py-0 sm:px-6 lg:flex-auto lg:px-0">
    <div class="mx-auto max-w-2xl space-y-16 sm:space-y-20 lg:mx-0 lg:max-w-none">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.profile.title' %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.profile.description' %></p>

        <%= form_with model: current_user, url: user_registration_path, class: 'md:col-span-2 mt-6 space-y-6 border-t border-gray-200 text-sm leading-6' do |f| %>
          <div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:max-w-xl sm:grid-cols-6 pt-6">
            <div class="col-span-full flex items-center gap-x-8" data-controller="image-preview">
              <% if current_user.avatar.present? %>
                <%= image_tag current_user.avatar, alt: '', class: 'h-20 w-20 flex-none rounded-lg bg-gray-100 object-cover', data: { target: 'image-preview.output' } %>
              <% else %>
                <%= image_tag image_path('default_avatar.svg'), alt: '', class: 'h-20 w-20 flex-none rounded-lg bg-gray-100 object-cover text-gray-300 fill-current', data: { target: 'image-preview.output' } %>
              <% end %>
              <div>
                <%= f.label :avatar, t('.profile.change_profile_image'), class: 'cursor-pointer rounded-md bg-indigo-600 px-3 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500' %>
                <%= f.file_field :avatar, direct_upload: true, class: 'sr-only', data: { target: 'image-preview.input', action: 'image-preview#readURL' } %>
                <p class="mt-2 text-xs leading-5 text-gray-400"><%= t '.profile.jpg_or_png_and_less_than_1mb' %></p>
              </div>
            </div>

            <div class="col-span-full">
              <%= f.label :name, t('.profile.name', class: 'block text-sm font-medium leading-6 text-gray-900') %>
              <div class="mt-2">
                <%= f.text_field :name, class: 'block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6' %>
              </div>
            </div>

            <div class="col-span-full">
              <%= f.label :email, t('.profile.email', class: 'block text-sm font-medium leading-6 text-gray-900') %>
              <div class="mt-2">
                <%= f.text_field :email, disabled: true, class: 'block w-full rounded-md border-0 bg-gray-200 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6' %>
              </div>
            </div>

            <div class="col-span-full">
              <%= f.label :locale, t('.profile.language'), class: 'block text-sm font-medium leading-6 text-gray-900' %>
              <div class="mt-2">
                <%= f.select :locale,
                             setting_language_and_locale_options,
                             {},
                             class: 'block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6 [&_*]:text-black' %>
              </div>
            </div>
          </div>

          <div class="mt-10 flex">
            <%= f.submit t('.save'), class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 cursor-pointer' %>
          </div>
        <% end %>
      </div>

      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.delete_account.title' %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.delete_account.description' %></p>

        <div class="flex items-start md:col-span-2 border-t border-gray-200 mt-6">
          <%= button_tag t('.delete_account.delete'),
                         class: 'rounded-md bg-red-500 mt-10 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-400 cursor-pointer',
                         data: { controller: 'modal', modal_dialog_param: 'delete_confirm_modal', action: 'click->modal#open' }%>
        </div>

        <dialog id="delete_confirm_modal" class="rounded-lg">
          <div class="relative transform overflow-hidden bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:w-full sm:max-w-lg sm:p-6">
            <div class="sm:flex sm:items-start">
              <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                </svg>
              </div>
              <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                <h3 class="text-base font-semibold leading-6 text-gray-900"><%= t '.delete_account.title' %></h3>
                <div class="mt-2">
                  <p class="text-sm text-gray-500"><%= t '.delete_account.detail_description_html' %></p>
                </div>
              </div>
            </div>
            <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
              <%= button_to t('.delete_account.delete'),
                            user_registration_path,
                            method: :delete,
                            class: 'inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto' %>
              <form method="dialog">
                <button type="submit" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto">
                  <%= t '.delete_account.cancel' %>
                </button>
              </form>
            </div>
          </div>
        </dialog>
      </div>
    </div>
  </div>
</div>

app/views/settings/notification.html.erb
<div class="w-full lg:flex lg:gap-x-16 lg:px-8 lg:mt-4">
  <%= render 'sidebar' %>

  <div class="px-4 py-16 py-20 lg:py-0 sm:px-6 lg:flex-auto lg:px-0">
    <div class="mx-auto max-w-2xl space-y-16 sm:space-y-20 lg:mx-0 lg:max-w-none">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.reminder.title' %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.reminder.description' %></p>

        <%= form_with model: @reminder_setting, class: 'md:col-span-2 mt-6 space-y-6 border-t border-gray-200 text-sm leading-6' do |f| %>
          <div class="grid grid-cols-6 gap-x-6 gap-y-8 sm:max-w-xl">
            <div class="mt-4 col-span-full">
              <span class="text-sm leading-6 text-gray-900"><%= t '.reminder.days' %></span>
              <div class="flex flex-wrap gap-2 mt-2">
                <%= f.collection_check_boxes :schedule_days, setting_days_options, :last, :first, { checked: @reminder_setting.schedule.days } do |b| %>
                  <div class="w-14">
                    <%= b.check_box class: 'sr-only peer' %>
                    <%= b.label class: 'cursor-pointer focus:outline-none ring-1 ring-inset ring-gray-300 bg-white text-gray-900 hover:bg-gray-50 flex items-center justify-center rounded-md py-3 px-2 text-sm font-semibold uppercase sm:flex-1 peer-checked:bg-indigo-500 peer-checked:text-white peer-checked:hover:bg-indigo-500' %>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="flex flex-col justify-center col-span-full">
              <%= f.label :schedule_time, t('.reminder.time') %>
              <%= f.time_field :schedule_time, class: 'mt-2 text-gray-900 rounded-md border-0 ring-1 ring-inset ring-gray-300' %>
            </div>

            <div class="flex flex-col justify-center col-span-full">
              <%= f.label :criteria_days, t('.reminder.criteria_days') %>
              <%= f.number_field :criteria_days, min: 0, class: 'mt-2 text-gray-900 rounded-md border-0 ring-1 ring-inset ring-gray-300' %>
            </div>

            <div class="col-span-full flex items-center">
              <label class="relative inline-flex items-center h-max cursor-pointer">
                <%= f.check_box :email, class: 'sr-only peer' %>
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-indigo-500 dark:peer-focus:ring-indigo-500 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-indigo-500"></div>
              </label>
              <%= f.label :email, t('.reminder.email_notification'), class: 'w-max ml-2 text-sm font-base text-gray-900 dark:text-gray-300' %>
            </div>
          </div>

          <div class="mt-10 flex">
            <%= f.submit t('.save'), class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 cursor-pointer' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/settings/summary.html.erb
<div class="w-full lg:flex lg:gap-x-16 lg:px-8 lg:mt-4">
  <%= render 'sidebar' %>

  <div class="px-4 py-16 py-20 lg:py-0 sm:px-6 lg:flex-auto lg:px-0">
    <div class="mx-auto max-w-2xl space-y-16 sm:space-y-20 lg:mx-0 lg:max-w-none">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.due_date.title' %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.due_date.description' %></p>

        <%= form_with model: @summary_setting, class: 'md:col-span-2 mt-6 space-y-6 border-t border-gray-200 text-sm leading-6' do |f| %>
          <div class="grid grid-cols-6 gap-x-6 gap-y-8 sm:max-w-xl">
            <div class="col-span-full">
              <%= f.label :name, t('.due_date.default_due_date', class: 'block text-sm font-medium leading-6 text-gray-900') %>
              <div class="mt-2">
                <%= f.number_field :default_due_days, class: 'block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6' %>
              </div>
            </div>
          </div>

          <div class="mt-10 flex">
            <%= f.submit t('.save'), class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 cursor-pointer' %>
          </div>
        <% end %>
      </div>

      <div class="">
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.ai.title' %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.ai.description' %></p>

        <%= form_with model: @summary_setting, class: 'md:col-span-2 mt-6 space-y-6 border-t border-gray-200 text-sm leading-6' do |f| %>
          <div class="grid grid-cols-6 gap-x-6 gap-y-8 sm:max-w-xl">
            <div class="col-span-full flex items-center">
              <label class="relative inline-flex items-center h-max cursor-pointer">
                <%= f.check_box :ai_summarizing_enabled, class: 'sr-only peer' %>
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-indigo-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-500"></div>
              </label>
              <%= f.label :ai_summarizing_enabled, t('.ai.ai_summarizing_enabled'), class: 'w-max ml-2 text-sm font-base text-gray-900' %>
            </div>

            <div class="col-span-full flex items-center">
              <label class="relative inline-flex items-center h-max cursor-pointer">
                <%= f.check_box :ai_tagging_enabled, class: 'sr-only peer' %>
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-indigo-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-500"></div>
              </label>
              <%= f.label :ai_tagging_enabled, t('.ai.ai_tagging_enabled'), class: 'w-max ml-2 text-sm font-base text-gray-900' %>
            </div>
          </div>

          <div class="mt-10 flex">
            <%= f.submit t('.save'), class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 cursor-pointer' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/settings/tag.html.erb
<div class="w-full lg:flex lg:gap-x-16 lg:px-8 lg:mt-4">
  <%= render 'sidebar' %>

  <div class="px-4 py-16 py-20 lg:py-0 sm:px-6 lg:flex-auto lg:px-0">
    <div class="mx-auto max-w-2xl space-y-16 sm:space-y-20 lg:mx-0 lg:max-w-none">
      <div class="w-full">
        <div class="sm:flex sm:items-center">
          <div class="sm:flex-auto">
            <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t '.tag.title' %></h2>
            <p class="mt-1 text-sm leading-6 text-gray-500"><%= t '.tag.description' %></p>
          </div>

          <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
            <%= link_to t('.tag.add_tag'),
                        new_links_tag_path,
                        class: 'block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600',
                        data: { turbo_stream: true } %>

          </div>
        </div>

        <table class="min-w-full divide-y divide-gray-300 mt-8">
          <thead>
            <tr>
              <th scope="col" class="w-3/6 sm:w-3/5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500"><%= t('.tag.name') %></th>
              <th scope="col" class="py-3 text-right text-xs font-medium uppercase tracking-wide text-gray-500"><%= t('.tag.used_count') %></th>
              <th scope="col" class="py-3 text-right text-xs font-medium uppercase tracking-wide text-gray-500"><%= t('.tag.edit') %></th>
              <th scope="col" class="py-3 text-right text-xs font-medium uppercase tracking-wide text-gray-500"><%= t('.tag.delete') %></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% @tags.each do |tag| %>
              <tr>
                <td class="whitespace-nowrap py-4">
                  <%= link_to tag.name,
                              links_path(q: { tags_name_in: [tag.name] }),
                              class: 'inline-flex items-center gap-x-0.5 rounded-md bg-indigo-50 px-2 py-1 text-xs sm:text-sm font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10' %>
                </td>
                <td class="whitespace-nowrap py-4 text-right text-sm font-base">
                  <%= tag.taggings_count %>
                </td>
                <td class="whitespace-nowrap py-4 text-right text-sm font-medium">
                  <%= link_to t('.tag.edit'),
                              edit_links_tag_path(tag),
                              class: 'text-indigo-600 hover:text-indigo-900',
                              data: { turbo_stream: true } %>
                </td>
                <td class="whitespace-nowrap py-4 text-right text-sm font-medium">
                  <%= link_to t('.tag.delete'),
                              links_tag_path(tag),
                              class: 'text-red-600 hover:text-red-700',
                              data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>