config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => '/good_job'
    mount Motor::Admin => '/admin'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root 'root#index'
  get 'direct_close' => 'root#direct_close', as: :direct_close
  get 'tos' => 'root#tos', as: :tos
  get 'privacy_policy' => 'root#privacy_policy', as: :privacy_policy

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :users, only: %i[] do
    collection do
      get 'me' => 'users#me'
    end
  end
  namespace :users do
    resources :reminder_settings, only: %i[create update]
    resources :summary_settings, only: %i[create update]
  end

  namespace :links do
    resources :tags, only: %i[index new create show edit update destroy]
  end
  resources :links, only: %i[index show new create edit update destroy] do
    collection do
      get 'others' => 'links#others'
    end
    member do
      put 'read' => 'links#read'
      put 'unread' => 'links#unread'
      post 'clone' => 'links#clone'
    end

    scope module: :links do
      resource :records, only: %i[show create edit update destroy]
    end
  end

  resources :settings, only: %i[] do
    collection do
      get 'general' => 'settings#general'
      get 'summary' => 'settings#summary'
      get 'notification' => 'settings#notification'
      get 'tag' => 'settings#tag'
    end
  end

  resources :notifications, only: %i[index]

  namespace :admin do
    resources :links, only: [] do
      collection do
        post 'initial' => 'links#create_initial'
      end
    end
  end
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  include Discard::Model
  include Taggable
  include Links::Scraping
  include Links::Searchable
  include Links::Readable
  include Links::Remindable

  belongs_to :user
  has_one :record, dependent: :destroy, class_name: 'Links::Record'
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings, class_name: 'Links::Tag'

  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :url, presence: true, uniqueness: { scope: :user_id }
  # rubocop:enable Rails/UniqueValidationWithoutIndex
  validates :due_date,
            comparison: { greater_than_or_equal_to: -> { Time.current.to_date }, allow_nil: true },
            if: :due_date_changed?

  before_validation :set_default_due_date, if: -> { due_date.blank? }, on: :create

  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  after_create_commit { broadcast_refresh_to [user, 'links'] }
  after_update_commit do
    I18n.with_locale(user.locale) do
      broadcast_replace_to [user, 'links'], locals: { link: self, current_user: user }
    end
    broadcast_refresh
  end
  after_discard do
    broadcast_remove_to [user, 'links']
    record.discard if record&.persisted?
  end
  after_undiscard -> { record&.undiscard }

  def clone(user_id)
    dup.tap do |link|
      link.user_id = user_id
      link.due_date = nil
      link.created_at = nil
    end
  end

  private

  def set_default_due_date
    self.due_date = user&.summary_setting&.default_due_days&.days&.from_now&.to_date
  end
end

app/models/link/readable.rb
# frozen_string_literal: true

module Link::Readable
  extend ActiveSupport::Concern

  def read!
    update!(read_at: Time.current)
  end

  def unread!
    update!(read_at: nil)
  end

  def read?
    read_at.present?
  end

  def unread?
    !read?
  end
end

app/models/link/scraping.rb
# frozen_string_literal: true

module Link::Scraping
  extend ActiveSupport::Concern

  included do
    enum scraping_state: { initial: 0, scraping: 1, completed: 2, failed: 3 }

    after_create_commit :scrap_later, if: :initial?
  end

  def scrap_now
    LinkScrapingJob.perform_now(self)
  end

  private

  def scrap_later
    LinkScrapingJob.perform_later(self)
  end
end

app/models/link/searchable.rb
# frozen_string_literal: true

module Link::Searchable
  extend ActiveSupport::Concern

  class_methods do
    def ransackable_attributes(_auth_object = nil)
      %w[title read_at]
    end

    def ransortable_attributes(_auth_object = nil)
      %w[id due_date]
    end
  end
end

app/models/links/application_record.rb
# frozen_string_literal: true

class Links::ApplicationRecord < ApplicationRecord
  self.abstract_class = true
  self.table_name_prefix = 'links_'
end

app/models/links/crawl_result.rb
# frozen_string_literal: true

class Links::CrawlResult
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :title, :string
  attribute :image_url, :string
  attribute :outline, :string
end

app/models/links/readable.rb
# frozen_string_literal: true

module Links::Readable
  extend ActiveSupport::Concern

  included do
    scope :read, -> { where.not(read_at: nil) }
    scope :unread, -> { where(read_at: nil) }
  end

  def read!
    update!(read_at: Time.current)
  end

  def unread!
    update!(read_at: nil)
  end

  def read?
    read_at.present?
  end

  def unread?
    !read?
  end

  def must_read?
    unread? && due_date.present?
  end
end

app/models/links/record.rb
# frozen_string_literal: true

class Links::Record < Links::ApplicationRecord
  include Discard::Model

  belongs_to :link

  validates :link, uniqueness: true
  validates :content, presence: true
end

app/models/links/remind_info.rb
# frozen_string_literal: true

class Links::RemindInfo
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Serializers::JSON

  attribute :id, :integer
  attribute :title, :string
  attribute :summary, :string
  attribute :due_date, :date
  attribute :url, :string
  attribute :created_at, :datetime

  def attributes
    {
      'id' => nil,
      'title' => nil,
      'summary' => nil,
      'due_date' => nil,
      'url' => nil,
      'created_at' => nil,
    }
  end
end

app/models/links/remindable.rb
# frozen_string_literal: true

module Links::Remindable
  extend ActiveSupport::Concern

  included do
    scope :remind_target, ->(criteria_days) do
      unread.where(due_date: ..criteria_days.days.from_now.to_date).order(due_date: :asc)
    end
  end

  def to_remind_info
    Links::RemindInfo.new(id:, title:, due_date:, url:, created_at:)
  end
end

app/models/links/searchable.rb
# frozen_string_literal: true

module Links::Searchable
  extend ActiveSupport::Concern

  class_methods do
    def ransackable_attributes(_auth_object = nil)
      %w[title read_at]
    end

    def ransortable_attributes(_auth_object = nil)
      %w[id due_date]
    end

    def ransackable_associations(_auth_object = nil)
      %w[tags]
    end
  end
end

app/models/links/tag.rb
# frozen_string_literal: true

class Links::Tag < Tag
  has_many :links, through: :taggings, source: :taggable, source_type: 'Link'

  scope :by_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
  scope :with_user, ->(user) { where(user:) }
  scope :with_user_id, ->(user_id) { where(user_id:) }
end

app/controllers/admin/links_controller.rb
# frozen_string_literal: true

class Admin::LinksController < Admin::ApplicationController
  def create_initial
    Link.create!(link_params)
  end

  private

  def link_params
    params.require(:link).permit(:url, :user_id, :due_date)
  end
end

app/controllers/links/records_controller.rb
# frozen_string_literal: true

class Links::RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link
  before_action :set_record, only: %i[show edit update destroy]

  def show; end

  def edit; end

  def create
    @record = @link.build_record(record_params)

    if @record.save
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = @record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  def update
    if @record.update(record_params)
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  def destroy
    if @record.destroy
      flash.now[:notice] = t('.success')
      render_record
    else
      flash.now[:alert] = record.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  private

  def set_link
    @link = current_user.links.find(params[:link_id])
  end

  def set_record
    @record = @link.record || @link.build_record
  end

  def record_params
    params.require(:links_record).permit(:link_id, :content)
  end

  def render_record
    render turbo_stream: turbo_stream.replace(
      [@link, 'record'],
      partial: 'links/records/record',
      locals: { record: @record },
    )
  end
end

app/controllers/links/tags_controller.rb
# frozen_string_literal: true

class Links::TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[edit update destroy]

  def index
    tags = Links::Tag.with_user(current_user).by_name(params[:q]).limit(10).pluck(:name)
    tags.unshift(params[:q]) if tags.exclude?(params[:q])

    respond_to do |format|
      format.json do
        render json: tags.map { |tag| { value: tag, text: tag } }
      end
    end
  end

  def new
    @tag = Links::Tag.new
  end

  def edit; end

  def create
    @tag = Links::Tag.new(tag_params.merge(user: current_user))
    if @tag.save
      redirect_to tag_settings_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tag_settings_path, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @tag.destroy
      redirect_to tag_settings_path, notice: t('.success')
    else
      flash.now[:alert] = @tag.errors.full_messages.first || t('.failure')
      render partial: 'shared/flash'
    end
  end

  private

  def tag_params
    params.require(:links_tag).permit(:name)
  end

  def set_tag
    @tag = Links::Tag.with_user(current_user).find(params[:id])
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  include Searchable

  before_action :authenticate_user!, except: %i[show]
  before_action :set_link, only: %i[edit update destroy read unread]

  MAX_ITEMS = 20

  def index
    @q = current_user.links.kept.includes(:tags).ransack(search_params)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @pagy, @links = pagy(@q.result(distinct: true), items: MAX_ITEMS)

    respond_to do |format|
      format.html
      format.json { render json: @links }
    end
  end

  def others
    links_with_distinct_url = Link.select('DISTINCT ON (url) *')
                                  .kept
                                  .completed
                                  .where.not(user_id: current_user.id)

    @q = Link.from(links_with_distinct_url, :links).ransack(search_params)
    @q.sorts = 'id desc' if @q.sorts.empty?
    @pagy, @links = pagy(@q.result, items: MAX_ITEMS)
  end

  def show
    @link = Link.kept.find(params[:id])
    @link.build_record if @link.record.blank?
  end

  def new
    @link = current_user.links.build
  end

  def edit; end

  def create
    @link = current_user.links.build(link_params)

    if @link.save
      respond_to do |format|
        format.json { render json: @link }
        format.html do
          flash[:notice] = t('.success')
          redirect_to link_path(@link)
        end
      end
    else
      logger.error @link.errors

      respond_to do |format|
        format.json { render json: @link.errors.full_messages, status: :unprocessable_entity }
        format.html do
          flash.now[:alert] = @link.errors.full_messages.first || t('.failure')
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    if @link.update(update_link_params)
      flash[:notice] = t('.success')
      redirect_to link_path(@link)
    else
      flash.now[:alert] = @link.errors.full_messages.first || t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.discard!
  end

  def read
    @link.read!
    render turbo_stream: turbo_stream.replace(
      [@link, 'menu'],
      partial: 'links/menu',
      locals: { link: @link },
    )
  end

  def unread
    @link.unread!
    render turbo_stream: turbo_stream.replace(
      [@link, 'menu'],
      partial: 'links/menu',
      locals: { link: @link },
    )
  end

  def clone
    cloned_link = Link.kept.find(params[:id]).clone(current_user.id)

    if cloned_link.save
      flash.now[:notice] = t('.clone.success')
    else
      flash.now[:alert] = cloned_link.errors.full_messages.first || t('.clone.failure')
    end

    render partial: 'shared/flash'
  end

  private

  def link_params
    params.require(:link).permit(:url, :due_date, tag_names: [])
  end

  def update_link_params
    params.require(:link).permit(:due_date, tag_names: [])
  end

  def set_link
    @link = current_user.links.kept.find(params[:id])
  end
end

app/helpers/link_helper.rb
# frozen_string_literal: true

module LinkHelper
  def link_until_due_date(due_date)
    distance_in_day = (due_date - Date.current).to_i

    classes = case distance_in_day
              when ..0
                'text-red-700 font-semibold'
              when 1..3
                'text-yellow-800 font-medium'
              when 4..7
                'text-blue-700 font-normal'
              else
                'text-green-700 font-normal'
              end

    content_tag :span, class: classes do
      if distance_in_day.negative?
        t('common.overdue')
      else
        left_time = distance_of_time_in_words(due_date.end_of_day, Time.current)
        t('common.some_left', value: left_time)
      end
    end
  end

  def link_sort_text_and_values
    [
      [t('links.index.newest'), 'id desc'],
      [t('links.index.oldest'), 'id asc'],
      [t('links.index.closest_due_date'), 'due_date asc'],
      [t('links.index.farthest_due_date'), 'due_date desc'],
    ]
  end

  def link_others_sort_text_and_values
    [
      [t('links.index.newest'), 'id desc'],
      [t('links.index.oldest'), 'id asc'],
    ]
  end

  def link_current_sort_value
    return nil if @q.sorts.empty?

    [@q.sorts.first.name, @q.sorts.first.dir].join(' ')
  end

  def link_image(url)
    url.presence || asset_path('default_background.png')
  end
end

app/views/links/_link.html.erb
<%= turbo_frame_tag link, class: 'h-full', target: '_top' do %>
  <li class="col-span-1 flex flex-col rounded-lg shadow h-full <%= link.read? && link.user_id == current_user&.id ? 'bg-slate-100' : 'bg-white' %>">
    <%= link_to link_path(link), class: 'flex flex-1 flex-col items-center px-6 sm:px-8 pt-6 sm:pt-8 h-80' do %>
      <% if link.completed? %>
        <div class="w-full h-32 bg-white/30 bg-center" style="background-image: url('<%= link_image(link.image_url) %>');">
          <div class="w-full h-full backdrop-blur-md flex justify-center items-center">
            <%= image_tag link_image(link.image_url), style: "view-transition-name: #{dom_id(link, :image)}", class: 'relative mx-auto max-w-full max-h-full flex-shrink-0 rounded-md object-contain', alt: 'link image' %>
            <object>
              <%= link_to link.url, class: 'absolute bottom-2 right-2 bg-gray-600 hover:bg-gray-700 text-white rounded-full p-2', form: { target: '_blank' } do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                </svg>
              <% end %>
            </object>
          </div>
        </div>

        <h3 class="mt-6 text-center text-base font-medium text-gray-900">
          <%= link.title %>
        </h3>
        <p class="text-left text-sm text-gray-500 line-clamp-5 text-ellipsis">
          <%= link.summary %>
        </p>
      <% elsif link.failed? %>
        <div class="animate-pulse bg-slate-200 mx-auto w-64 h-32 flex-shrink-0 rounded-md"></div>
        <h3 class="mt-6 text-center text-sm font-medium text-gray-900">
          <%= t('.failed') %>
        </h3>
        <p class="text-left text-sm text-gray-500 line-clamp-5 text-ellipsis">
        </p>
      <% else %>
        <div class="animate-pulse bg-slate-200 mx-auto w-64 h-32 flex-shrink-0 rounded-md"></div>
        <h3 class="mt-6 text-center text-sm font-medium text-gray-900">
          <%= t('.loading') %>
        </h3>
        <p class="text-left text-sm text-gray-500 line-clamp-5 text-ellipsis">
        </p>
      <% end %>
    <% end %>

    <div class="w-full px-6 sm:px-8 py-3">
      <% if link.user_id == current_user&.id %>
        <ul class="flex flex-row gap-x-1.5 sm:gap-x-2.5">
          <%= render partial: 'links/tag', collection: link.tags %>
        </ul>
      <% end %>
    </div>

    <div class="flex flex-column justify-between items-center px-6 sm:px-8 py-3 text-xs font-normal border-t border-gray-200">
      <div class="flex">
        <span class="text-gray-500">
          <%= relative_time(link.created_at) %>
        </span>
        <% if link.must_read? && link.user_id == current_user&.id %>
          <div class="ml-3 border-l border-gray-200 pl-3">
            <%= link_until_due_date(link.due_date) %>
          </div>
        <% end %>
      </div>

      <div class="relative flex sm:hidden" data-controller="dropdown">
        <button type="button" class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500" data-action="dropdown#toggle click@window->dropdown#hide">
          <span class="sr-only">Open options</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path d="M3 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM8.5 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM15.5 8.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
          </svg>
        </button>

        <div class="hidden absolute right-0 z-10 mt-2 w-32 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
             data-dropdown-target="menu"
             data-transition-enter-from="opacity-0 scale-95"
             data-transition-enter-to="opacity-100 scale-100"
             data-transition-leave-from="opacity-100 scale-100"
             data-transition-leave-to="opacity-0 scale-95">

          <% if link.user_id == current_user&.id %>
            <% if link.read? %>
              <%= link_to t('.unread'), unread_link_path(link), class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left', data: { turbo_method: :put } %>
            <% else %>
              <%= link_to t('.read'), read_link_path(link), class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left', data: { turbo_method: :put } %>
            <% end %>
            <%= link_to t('.edit'), edit_link_path(link), class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left' %>
            <%= link_to t('.delete'), link_path(link), class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left', data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') } %>
          <% else %>
            <%= link_to t('.clone_to_my'), clone_link_path(link), class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left', data: { turbo_method: :post } %>
          <% end %>
        </div>
      </div>

      <div class="hidden sm:flex">
        <% if link.user_id == current_user&.id %>
          <% if link.read? %>
            <%= link_to t('.unread'), unread_link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :put } %>
          <% else %>
            <%= link_to t('.read'), read_link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :put } %>
          <% end %>

          <div class="ml-3 border-l border-gray-200 pl-3">
            <%= link_to t('.edit'), edit_link_path(link), class: 'text-indigo-600 hover:text-indigo-500' %>
          </div>
          <div class="ml-3 border-l border-gray-200 pl-3">
            <%= link_to t('.delete'), link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') } %>
          </div>
        <% else %>
          <%= link_to t('.clone_to_my'), clone_link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :post } %>
        <% end %>
      </div>
    </div>
  </li>
<% end %>

app/views/links/_links.html.erb
<%# locals: (paging: true) %>

<% if @links.present? %>
  <ul role="list">
    <%= turbo_frame_tag 'links', data: { turbo_action: 'advance' }, class: 'grid grid-cols-1 gap-6 lg:grid-cols-2 mt-10 sm:mt-14' do %>
      <%= render @links %>
    <% end %>
  </ul>

  <% if paging %>
    <div class="flex justify-center mt-8 lg:mt-16 w-full">
      <%== pagy_nav @pagy, link_extra: 'data-turbo-action="advance"' %>
    </div>
  <% end %>
<% else %>
  <div class="text-center mt-10 sm:mt-14">
    <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
    </svg>
    <h3 class="mt-2 text-sm font-semibold text-gray-900"><%= t('.not_exist') %></h3>
    <p class="mt-1 text-sm text-gray-500"><%= t('.get_started_by_adding_a_new_link') %></p>
    <div class="mt-6">
      <%= link_to new_link_path, class: 'inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600', data: { turbo_frame: '_top' } do %>
        <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
        </svg>
        <%= t('.new_link') %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/links/_menu.html.erb
<%# locals: (link:) %>

<%= turbo_frame_tag link, 'menu', class: "flex mt-8 text-sm" do %>
  <% if link.user_id == current_user&.id %>
    <% if link.read? %>
      <%= link_to t('.unread'), unread_link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :put } %>
    <% else %>
      <%= link_to t('.read'), read_link_path(link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :put } %>
    <% end %>

    <div class="ml-3 border-l border-gray-200 pl-3">
      <%= link_to t('.edit'), edit_link_path(@link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_frame: '_top' } %>
    </div>
    <div class="ml-3 border-l border-gray-200 pl-3">
      <%= link_to t('.delete'), link_path(@link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') } %>
    </div>
  <% else %>
    <%= link_to t('.clone_to_my'), clone_link_path(@link), class: 'text-indigo-600 hover:text-indigo-500', data: { turbo_method: :post } %>
  <% end %>
<% end %>

app/views/links/_tag.html.erb
<%# locals: (tag:) %>

<li>
  <%= link_to tag.name,
              links_path(q: { tags_name_in: [tag.name] }),
              class: 'inline-flex items-center gap-x-0.5 rounded-md bg-indigo-50 px-2 py-1 text-xs sm:text-sm font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10' %>
</li>

app/views/links/edit.html.erb
<%= render 'form', link: @link, title: t('.title') %>

app/views/links/others.html.erb
<%= turbo_stream_from 'links' %>

<div class="w-full">
  <div class="flex flex-col w-full">
    <div class="flex justify-between items-normal">
      <%= search_form_for @q, url: others_links_path, class: 'flex flex-col sm:items-center sm:flex-row', data: { controller: 'search', turbo_frame: 'links', turbo_action: 'advance' } do |f| %>
        <div class="relative w-48 md:w-60 lg:w-72">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <svg class="h4 sm:h-5 w-4 sm:w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
            </svg>
          </div>

          <%= f.search_field :title_cont, class: 'block w-full rounded-md border-0 bg-white py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 text-xs sm:text-sm sm:leading-6', placeholder: 'Search', data: { action: 'input->search#search' } %>
        </div>

        <div class="flex items-center mt-2 sm:mt-0 ml-0 sm:ml-3">
          <%= f.select :s,
                       options_for_select(link_others_sort_text_and_values, link_current_sort_value),
                       {},
                       class: 'w-28 sm:w-32 border-0 justify-between inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-xs sm:text-sm font-medium text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50',
                       data: { action: 'change->search#search' } %>
        </div>
      <% end %>

      <%= link_to t('links.index.new'), new_link_path, class: 'h-max ml-6 inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600', data: { action: 'click->modal#open' } %>
    </div>

    <%= render 'links/links'%>
  </div>
</div>