config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => '/good_job'
    mount Motor::Admin => '/admin'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root 'root#index'
  get 'direct_close' => 'root#direct_close', as: :direct_close
  get 'tos' => 'root#tos', as: :tos
  get 'privacy_policy' => 'root#privacy_policy', as: :privacy_policy

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :users, only: %i[] do
    collection do
      get 'me' => 'users#me'
    end
  end
  namespace :users do
    resources :reminder_settings, only: %i[create update]
    resources :summary_settings, only: %i[create update]
  end

  namespace :links do
    resources :tags, only: %i[index new create show edit update destroy]
  end
  resources :links, only: %i[index show new create edit update destroy] do
    collection do
      get 'others' => 'links#others'
    end
    member do
      put 'read' => 'links#read'
      put 'unread' => 'links#unread'
      post 'clone' => 'links#clone'
    end

    scope module: :links do
      resource :records, only: %i[show create edit update destroy]
    end
  end

  resources :settings, only: %i[] do
    collection do
      get 'general' => 'settings#general'
      get 'summary' => 'settings#summary'
      get 'notification' => 'settings#notification'
      get 'tag' => 'settings#tag'
    end
  end

  resources :notifications, only: %i[index]

  namespace :admin do
    resources :links, only: [] do
      collection do
        post 'initial' => 'links#create_initial'
      end
    end
  end
end

app/views/layouts/_avatar.html.erb
<%= turbo_frame_tag current_user, 'avatar', target: '_top' do %>
  <% if user_signed_in? %>
    <div class="relative" data-controller="dropdown">
      <button type="button" class="relative flex rounded-full bg-white text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" data-action="dropdown#toggle click@window->dropdown#hide">
        <span class="absolute -inset-1.5"></span>
        <span class="sr-only">Open user menu</span>

        <% if current_user.avatar.present? %>
          <%= image_tag current_user.avatar, class: 'h-8 w-8 rounded-full' %>
        <% else %>
          <%= image_tag image_path('default_avatar.svg'), alt: '', class: 'h-8 w-8 rounded-full bg-gray-100' %>
        <% end %>
      </button>

      <div class="hidden absolute right-0 z-10 mt-2 w-32 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
           data-dropdown-target="menu"
           data-transition-enter-from="opacity-0 scale-95"
           data-transition-enter-to="opacity-100 scale-100"
           data-transition-leave-from="opacity-100 scale-100"
           data-transition-leave-to="opacity-0 scale-95">
        <%= link_to t('.setting'), general_settings_path, class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left' %>
        <%= link_to t('.sign_out'),
                      destroy_user_session_path,
                      class: 'block px-4 py-2 text-sm text-gray-700 w-full text-left',
                      data: { action: 'dropdown#toggle', turbo_method: :delete, turbo_confirm: t('.confirm_sign_out') } %>
      </div>
    </div>
  <% else %>
    <%= button_to t('.sign_in'),
                  user_google_oauth2_omniauth_authorize_path,
                  method: :post,
                  class: 'text-base font-medium leading-6 text-gray-900',
                  data: { turbo: false }
    %>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<%# locals: (type:, message:) %>

<div
  class="hidden transition transform duration-500 flex w-full flex-col items-center space-y-4 sm:items-end"
  data-controller="flash"
  data-flash-delay-value="5000"
  data-transition-enter-from="opacity-0 translate-x-6"
  data-transition-enter-to="opacity-100 translate-x-0"
  data-transition-leave-from="opacity-100 translate-x-0"
  data-transition-leave-to="opacity-0 translate-x-6"
  data-action="animationend->removals#remove">
  <div class="p-4 flex flex-start pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
    <div class="flex-shrink-0">
      <%= flash_svg(type) %>
    </div>
    <div class="ml-3 w-0 flex-1 pt-0.5">
      <p class="text-sm font-medium text-gray-900"><%= message %></p>
    </div>
    <div class="ml-4 flex flex-shrink-0">
      <button type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" data-action="flash#hide">
        <span class="sr-only">Close</span>
        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
        </svg>
      </button>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-white w-full border-t border-gray-900/10 mt-12">
  <div class="mx-auto max-w-7xl px-6 py-12 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center space-x-6 md:order-2">
      <a href="https://github.com/No-YE/todo-rist" class="text-gray-400 hover:text-gray-500" target="_blank">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
    <div class="mt-8 md:order-1 md:mt-0">
      <p class="text-center text-xs leading-5 text-gray-500">&copy; 2024 Enowhy. All rights reserved.</p>
      <div class="mt-1 flex gap-x-2 justify-center md:justify-start">
        <%= link_to t('.tos'), tos_url, class: 'text-xs text-gray-500', target: '_blank' %>
        <%= link_to t('.privacy'), privacy_policy_url, class: 'text-xs text-gray-500', target: '_blank' %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="w-full" data-controller="collapse">
  <div class="w-full flex items-center justify-between py-6">
    <div class="flex flex-1">
      <% if user_signed_in? %>
        <button type="button" class="sm:hidden relative inline-flex mr-1 items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" data-action="click->collapse#toggle">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      <% end %>

      <%= link_to root_path, class: 'flex flex-column items-center p-1.5 -m-1.5' do %>
        <%= image_tag 'logo_lg.svg', class: 'hidden sm:inline-block' %>
        <%= image_tag 'logo_sm.svg', class: 'inline-block sm:hidden' %>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <div class="hidden sm:flex sm:gap-x-12 sm:items-center">
        <%= link_to t('.my_rist'), links_path, class: "text-sm font-semibold leading-6 #{current_page?(controller: '/links', action: 'index') ? 'text-gray-900' : 'text-gray-500 hover:text-gray-700'}" %>
        <%= link_to t('.others_rist'), others_links_path, class: "text-sm font-semibold leading-6 #{current_page?(controller: '/links', action: 'others') ? 'text-gray-900' : 'text-gray-500 hover:text-gray-700'}" %>
      </div>
    <% end %>

    <div class="flex flex-1 justify-end gap-x-3">
      <%= render 'layouts/notification' %>
      <%= render 'layouts/avatar' %>
    </div>
  </div>

  <div class="hidden sm:hidden flow-root px-2" data-collapse-target="collapse">
    <div class="divide-y divide-gray-500/10 mb-2 -mt-4">
      <%= link_to t('.my_rist'), links_path, class: "-mx-3 block rounded-lg px-3 py-2 text-base font-medium leading-7 text-gray-900 hover:bg-gray-50 #{current_page?(controller: '/links', action: 'index') ? 'bg-gray-100' : 'bg-white'}" %>
      <%= link_to t('.others_rist'), others_links_path, class: "-mx-3 block rounded-lg px-3 py-2 text-base font-medium leading-7 text-gray-900 hover:bg-gray-50 #{current_page?(controller: '/links', action: 'others') ? 'bg-gray-100' : 'bg-white'}" %> </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<% if user_signed_in? %>
    <%= link_to notifications_path, class: 'flex items-center p-1 text-gray-400 hover:text-gray-500' do %>
    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
    </svg>

    <% if current_user.notifications.unread.exists? %>
      <div class="relative w-1.5 h-1.5 -top-2 -left-2 bg-red-700 rounded-full inline-block"></div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>TodoRist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css" />
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet" />
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= display_meta_tags site: 'todorist' %>

    <%= favicon_link_tag asset_path('logo_sm.svg') %>

    <%= turbo_refreshes_with method: :morph, scroll: :preserve  %>
    <%= content_for :head %>

    <meta name="turbo-cache-control" content="no-cache">
    <meta name="view-transition" content="same-origin">
  </head>

  <body>
    <header class="container mx-auto px-5 flex max-w-7xl">
      <%= render 'layouts/header' %>
    </header>
    <main class="container mx-auto mt-8 sm:mt-12 px-5 flex max-w-7xl">
      <%= yield %>
    </main>
    <footer class="container mx-auto px-5 flex max-w-7xl">
      <%= render 'layouts/footer' %>
    </footer>

    <%= turbo_frame_tag :flashes, class: 'pointer-events-none fixed inset-0 flex flex-col items-end px-4 py-6 sm:p-6' do %>
      <%= render 'shared/flash' %>
    <% end%>
    <remote-modal-container></remote-modal-container>

    <script>
      (function(){var w=window;if(w.ChannelIO){return w.console.error("ChannelIO script included twice.");}var ch=function(){ch.c(arguments);};ch.q=[];ch.c=function(args){ch.q.push(args);};w.ChannelIO=ch;function l(){if(w.ChannelIOInitialized){return;}w.ChannelIOInitialized=true;var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src="https://cdn.channel.io/plugin/ch-plugin-web.js";var x=document.getElementsByTagName("script")[0];if(x.parentNode){x.parentNode.insertBefore(s,x);}}if(document.readyState==="complete"){l();}else{w.addEventListener("DOMContentLoaded",l);w.addEventListener("load",l);}})();

      ChannelIO('boot', {
        "pluginKey": "02a969d0-1d86-4de7-b77a-ecdfe8523be9"
      });
    </script>
  </body>
</html>

app/views/layouts/application.turbo_stream.erb
<%= render 'shared/flash' %>
<%= yield %>